export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE'
}

export const productsConstants = {
    GET_PRODUCTS_DETAILS_BY_ID_REQUEST:'GET_PRODUCTS_DETAILS_BY_ID_REQUEST',
    GET_PRODUCTS_DETAILS_BY_ID_SUCCESS:'GET_PRODUCTS_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCTS_DETAILS_BY_ID_FAILURE:'GET_PRODUCTS_DETAILS_BY_ID_FAILURE',

    GET_PRODUCTS_BY_SLUG: 'GET_PRODUCTS_BY_SLUG',
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',
}

export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}